encyclopedia/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/new/", views.new_page, name="new_page"),
    path("wiki/random/", views.random_page, name="random_page"),
    path("wiki/edit/<str:title>", views.edit_page, name="edit_page"),
    path("wiki/<str:title>", views.entry_page, name="entry_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

# helps in stoping caching of static files
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]


# stops caching of static files
# https://stackoverflow.com/a/54222112/6008082
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import re
import random
from django.shortcuts import render, resolve_url
from django.http import HttpResponseRedirect
from django.urls import reverse
from markdown2 import markdown

from . import util



# displays home page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


# display entry page of the given entry
def entry_page(request, title):
    # get content from the entry
    entry_content = util.get_entry(title)

    # check if entry is present or not
    if entry_content == None:
        return render(request, "encyclopedia/errors/notfound.html")
    

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry_content": markdown(entry_content, safe_mode = "escape"),
    })


# search for a given entry if found display that entry otherwise display matched results
def search(request):
    query = str(request.GET["q"])
    
    # entry exist then redirect to entry_page
    if util.get_entry(query.title()):
        return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[query.title()]))

    entries = util.list_entries()

    # find similar entries - case insensitive search with lowercase
    results = [entry for entry in entries if query.lower() in entry.lower() or entry.lower() in query.lower()]

    return render(request, 'encyclopedia/searchresult.html', {
        "query": query,
        "results": results,
    })


# adds new page in the disk by taking input from the user
def new_page(request):
    if request.method == "POST":
        title = str(request.POST["title"])
        content = str(request.POST["content"])

        # if page already exist then show error
        all_entries = [entry.lower() for entry in util.list_entries()]
        if title.lower() in all_entries:
            return render(request, 'encyclopedia/errors/alreadyexist.html', {
                "title": title.capitalize(),
            })

        # add page to the disk and take user to the new page
        util.save_entry(title, content)

        return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[title]))     
    else:
        return render(request, 'encyclopedia/newpage.html')

# display a page for editing and edit it on POST request
def edit_page(request, title):
    if request.method == "POST":
        new_title = str(request.POST["title"])
        new_content = str(request.POST["content"])

        # add page to the disk and take user to the new page
        # Using util.edit() instead of save_entry ensures that two files will not be created
        # when editing an old file with new title name.
        util.edit_entry(title, new_title, new_content)

        return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[new_title]))
    else:
        content = util.get_entry(title)

        return render(request, 'encyclopedia/editpage.html', {
            "title": title,
            "content": content,
    })

def random_page(request):
    titles = util.list_entries()
    # if no title exist no random can be displayed
    if len(titles) == 0:
        return render(request, 'encyclopedia/notfound.html')
    
    # select a random title
    random_title = random.choice(titles)

    # redirect to entry page of random title
    return HttpResponseRedirect(reverse('encyclopedia:entry_page', args = [random_title]))

encyclopedia/templates/encyclopedia/editpage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Edit {{title}}
{% endblock %}

{% block main %}
    <h1 class="text-center">Edit {{title}}'s Page</h1>
    <div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <label for="id_title" class="input-group-text">Title:</label>
            </div>
            <input type="text" name="title" id="id_title" class="form-control" value="{{title}}" required>
        </div>
        <div class="form-group">
            <textarea name="content" id="id_content" class="form-control" rows="20" required>{{content}}</textarea>
        </div>
        <button type="submit" class="btn btn-dark">Save This Page</button>
    </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{title}}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="entry-content">
            {{entry_content | safe}}
        </div>
        <a href="{% url 'encyclopedia:edit_page' title%}" class="btn btn-dark">Edit This Page</a>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block main %}
    <h1 class="text-center">All Pages</h1>

    <ul class="list-group list-group-flush">
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:entry_page' entry %}" class="list-group-item list-group-item-action">{{entry}}</a>
        {% empty %}
            <div class="alert alert-warning">No Page Exist</div>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script> -->

        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-4">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <div class="form-group">
                        <input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia" required>
                    </div>
                </form>
                <nav id="main-nav">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a href="{% url 'encyclopedia:index'%}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'encyclopedia:new_page'%}" class="nav-link">Create New Page</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'encyclopedia:random_page' %}" class="nav-link">Random Page</a>
                        </li>
                    </ul>
                </nav>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main container col-lg-10 col-md-8">
                {% block main %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Add New Page
{% endblock %}

{% block main %}
    <h1 class="text-center">Add a New Page</h1>
    <div class="container">
    <form action="{% url 'encyclopedia:new_page'%}" method="POST">
        {% csrf_token %}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <label for="id_title" class="input-group-text">Title:</label>
            </div>
            <input type="text" name="title" id="id_title" class="form-control" required>
        </div>
        <div class="form-group">
            <textarea name="content" id="id_content" class="form-control" rows="20" placeholder="Enter content in markdown here." required></textarea>
        </div>
        <button type="submit" class="btn btn-dark">Add This Page</button>
    </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/searchresult.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block main %}
    <h1 class="text-center">Matched Searched Results for {{query}}</h1>

    {%if results%}
        <div class="alert alert-success">{{results|length}} result found.</div>
    {% endif %}
    <ul class="list-group list-group-flush">
        {% for result in results %}
            <a href="{% url 'encyclopedia:entry_page' result %}" class="list-group-item list-group-item-action">{{result}}</a>
            {% empty %}
                <div class="alert text-center alert-warning">No Result Found</div>
        {% endfor %}
    </ul>

{% endblock %}